package com.thayer.idsservice.task.update.bean;

import java.io.Serializable;

public class TProp implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -475401770113692086L;
	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String prop;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getProp() {
		return prop;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setProp(String prop) {
		this.prop = prop;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String orgid;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getOrgid() {
		return orgid;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String propNameJp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getPropNameJp() {
		return propNameJp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPropNameJp(String propNameJp) {
		this.propNameJp = propNameJp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String propNameEn;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getPropNameEn() {
		return propNameEn;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPropNameEn(String propNameEn) {
		this.propNameEn = propNameEn;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String propNameZh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getPropNameZh() {
		return propNameZh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPropNameZh(String propNameZh) {
		this.propNameZh = propNameZh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String address1Zh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAddress1Zh() {
		return address1Zh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddress1Zh(String address1Zh) {
		this.address1Zh = address1Zh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String address1En;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAddress1En() {
		return address1En;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddress1En(String address1En) {
		this.address1En = address1En;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String address1Jp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAddress1Jp() {
		return address1Jp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddress1Jp(String address1Jp) {
		this.address1Jp = address1Jp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String address2Zh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAddress2Zh() {
		return address2Zh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddress2Zh(String address2Zh) {
		this.address2Zh = address2Zh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String address2En;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAddress2En() {
		return address2En;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddress2En(String address2En) {
		this.address2En = address2En;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String address2Jp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAddress2Jp() {
		return address2Jp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddress2Jp(String address2Jp) {
		this.address2Jp = address2Jp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String areaid;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getAreaid() {
		return areaid;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String countryid;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getCountryid() {
		return countryid;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setCountryid(String countryid) {
		this.countryid = countryid;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String cityid;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getCityid() {
		return cityid;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setCityid(String cityid) {
		this.cityid = cityid;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String propTypeid;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getPropTypeid() {
		return propTypeid;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPropTypeid(String propTypeid) {
		this.propTypeid = propTypeid;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String zip;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String status;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String phone;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String fax;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String timezone;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getTimezone() {
		return timezone;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date checkin;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getCheckin() {
		return checkin;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setCheckin(java.util.Date checkin) {
		this.checkin = checkin;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date lateCheckin;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getLateCheckin() {
		return lateCheckin;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setLateCheckin(java.util.Date lateCheckin) {
		this.lateCheckin = lateCheckin;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date checkout;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getCheckout() {
		return checkout;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setCheckout(java.util.Date checkout) {
		this.checkout = checkout;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date holdtime;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getHoldtime() {
		return holdtime;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setHoldtime(java.util.Date holdtime) {
		this.holdtime = holdtime;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date openingDate;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getOpeningDate() {
		return openingDate;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setOpeningDate(java.util.Date openingDate) {
		this.openingDate = openingDate;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date renovatedDate;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getRenovatedDate() {
		return renovatedDate;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setRenovatedDate(java.util.Date renovatedDate) {
		this.renovatedDate = renovatedDate;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String descriptionZh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getDescriptionZh() {
		return descriptionZh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setDescriptionZh(String descriptionZh) {
		this.descriptionZh = descriptionZh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String descriptionEn;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getDescriptionEn() {
		return descriptionEn;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setDescriptionEn(String descriptionEn) {
		this.descriptionEn = descriptionEn;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String descriptionJp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getDescriptionJp() {
		return descriptionJp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setDescriptionJp(String descriptionJp) {
		this.descriptionJp = descriptionJp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String latitude;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String longitude;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String needPay;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getNeedPay() {
		return needPay;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setNeedPay(String needPay) {
		this.needPay = needPay;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal starRating;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getStarRating() {
		return starRating;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setStarRating(java.math.BigDecimal starRating) {
		this.starRating = starRating;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal diamondRating;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getDiamondRating() {
		return diamondRating;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setDiamondRating(java.math.BigDecimal diamondRating) {
		this.diamondRating = diamondRating;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal priceHigh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getPriceHigh() {
		return priceHigh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPriceHigh(java.math.BigDecimal priceHigh) {
		this.priceHigh = priceHigh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal priceLow;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getPriceLow() {
		return priceLow;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPriceLow(java.math.BigDecimal priceLow) {
		this.priceLow = priceLow;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal totalRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getTotalRooms() {
		return totalRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setTotalRooms(java.math.BigDecimal totalRooms) {
		this.totalRooms = totalRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal totalFloors;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getTotalFloors() {
		return totalFloors;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setTotalFloors(java.math.BigDecimal totalFloors) {
		this.totalFloors = totalFloors;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactNameZh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactNameZh() {
		return contactNameZh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactNameZh(String contactNameZh) {
		this.contactNameZh = contactNameZh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactNameEn;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactNameEn() {
		return contactNameEn;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactNameEn(String contactNameEn) {
		this.contactNameEn = contactNameEn;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactNameJp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactNameJp() {
		return contactNameJp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactNameJp(String contactNameJp) {
		this.contactNameJp = contactNameJp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactTitleZh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactTitleZh() {
		return contactTitleZh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactTitleZh(String contactTitleZh) {
		this.contactTitleZh = contactTitleZh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactTitleEn;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactTitleEn() {
		return contactTitleEn;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactTitleEn(String contactTitleEn) {
		this.contactTitleEn = contactTitleEn;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactTitleJp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactTitleJp() {
		return contactTitleJp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactTitleJp(String contactTitleJp) {
		this.contactTitleJp = contactTitleJp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactPhone;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String contactEmail;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getContactEmail() {
		return contactEmail;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date activatedDate;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getActivatedDate() {
		return activatedDate;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setActivatedDate(java.util.Date activatedDate) {
		this.activatedDate = activatedDate;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date modifyDate;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setModifyDate(java.util.Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String modifyUser;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal totalElevators;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getTotalElevators() {
		return totalElevators;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setTotalElevators(java.math.BigDecimal totalElevators) {
		this.totalElevators = totalElevators;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal doubleRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getDoubleRooms() {
		return doubleRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setDoubleRooms(java.math.BigDecimal doubleRooms) {
		this.doubleRooms = doubleRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal handiRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getHandiRooms() {
		return handiRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setHandiRooms(java.math.BigDecimal handiRooms) {
		this.handiRooms = handiRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal kingRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getKingRooms() {
		return kingRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setKingRooms(java.math.BigDecimal kingRooms) {
		this.kingRooms = kingRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal meetRoomCap;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getMeetRoomCap() {
		return meetRoomCap;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setMeetRoomCap(java.math.BigDecimal meetRoomCap) {
		this.meetRoomCap = meetRoomCap;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal maxPropBednum;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getMaxPropBednum() {
		return maxPropBednum;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setMaxPropBednum(java.math.BigDecimal maxPropBednum) {
		this.maxPropBednum = maxPropBednum;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal meetingRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getMeetingRooms() {
		return meetingRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setMeetingRooms(java.math.BigDecimal meetingRooms) {
		this.meetingRooms = meetingRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal meetRoomArea;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getMeetRoomArea() {
		return meetRoomArea;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setMeetRoomArea(java.math.BigDecimal meetRoomArea) {
		this.meetRoomArea = meetRoomArea;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal nosmokingRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getNosmokingRooms() {
		return nosmokingRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setNosmokingRooms(java.math.BigDecimal nosmokingRooms) {
		this.nosmokingRooms = nosmokingRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal twinRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getTwinRooms() {
		return twinRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setTwinRooms(java.math.BigDecimal twinRooms) {
		this.twinRooms = twinRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal queenRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getQueenRooms() {
		return queenRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setQueenRooms(java.math.BigDecimal queenRooms) {
		this.queenRooms = queenRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal addExtraBed;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getAddExtraBed() {
		return addExtraBed;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAddExtraBed(java.math.BigDecimal addExtraBed) {
		this.addExtraBed = addExtraBed;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal bigRooms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getBigRooms() {
		return bigRooms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setBigRooms(java.math.BigDecimal bigRooms) {
		this.bigRooms = bigRooms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String website;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal isModel;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getIsModel() {
		return isModel;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setIsModel(java.math.BigDecimal isModel) {
		this.isModel = isModel;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal feeLow;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getFeeLow() {
		return feeLow;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setFeeLow(java.math.BigDecimal feeLow) {
		this.feeLow = feeLow;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode1;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode1() {
		return gdscode1;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode1(String gdscode1) {
		this.gdscode1 = gdscode1;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode2;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode2() {
		return gdscode2;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode2(String gdscode2) {
		this.gdscode2 = gdscode2;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date gdscode3;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getGdscode3() {
		return gdscode3;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode3(java.util.Date gdscode3) {
		this.gdscode3 = gdscode3;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode4;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode4() {
		return gdscode4;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode4(String gdscode4) {
		this.gdscode4 = gdscode4;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode5;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode5() {
		return gdscode5;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode5(String gdscode5) {
		this.gdscode5 = gdscode5;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date gdscode6;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getGdscode6() {
		return gdscode6;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode6(java.util.Date gdscode6) {
		this.gdscode6 = gdscode6;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode7;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode7() {
		return gdscode7;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode7(String gdscode7) {
		this.gdscode7 = gdscode7;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode8;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode8() {
		return gdscode8;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode8(String gdscode8) {
		this.gdscode8 = gdscode8;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date gdscode9;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getGdscode9() {
		return gdscode9;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode9(java.util.Date gdscode9) {
		this.gdscode9 = gdscode9;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode10;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode10() {
		return gdscode10;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode10(String gdscode10) {
		this.gdscode10 = gdscode10;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode11;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode11() {
		return gdscode11;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode11(String gdscode11) {
		this.gdscode11 = gdscode11;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date gdscode12;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getGdscode12() {
		return gdscode12;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode12(java.util.Date gdscode12) {
		this.gdscode12 = gdscode12;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode13;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode13() {
		return gdscode13;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode13(String gdscode13) {
		this.gdscode13 = gdscode13;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String gdscode14;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getGdscode14() {
		return gdscode14;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode14(String gdscode14) {
		this.gdscode14 = gdscode14;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date gdscode15;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getGdscode15() {
		return gdscode15;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setGdscode15(java.util.Date gdscode15) {
		this.gdscode15 = gdscode15;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal lowLimit;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getLowLimit() {
		return lowLimit;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setLowLimit(java.math.BigDecimal lowLimit) {
		this.lowLimit = lowLimit;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal highLimit;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getHighLimit() {
		return highLimit;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setHighLimit(java.math.BigDecimal highLimit) {
		this.highLimit = highLimit;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal propcat;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getPropcat() {
		return propcat;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setPropcat(java.math.BigDecimal propcat) {
		this.propcat = propcat;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String districtid;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getDistrictid() {
		return districtid;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setDistrictid(String districtid) {
		this.districtid = districtid;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal isWelcomeForeign;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getIsWelcomeForeign() {
		return isWelcomeForeign;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setIsWelcomeForeign(java.math.BigDecimal isWelcomeForeign) {
		this.isWelcomeForeign = isWelcomeForeign;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal isFaith;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getIsFaith() {
		return isFaith;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setIsFaith(java.math.BigDecimal isFaith) {
		this.isFaith = isFaith;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal censor;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getCensor() {
		return censor;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setCensor(java.math.BigDecimal censor) {
		this.censor = censor;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal isPms;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getIsPms() {
		return isPms;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setIsPms(java.math.BigDecimal isPms) {
		this.isPms = isPms;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String keywords;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String simpleDescZh;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getSimpleDescZh() {
		return simpleDescZh;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setSimpleDescZh(String simpleDescZh) {
		this.simpleDescZh = simpleDescZh;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String simpleDescEn;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getSimpleDescEn() {
		return simpleDescEn;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setSimpleDescEn(String simpleDescEn) {
		this.simpleDescEn = simpleDescEn;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String simpleDescJp;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getSimpleDescJp() {
		return simpleDescJp;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setSimpleDescJp(String simpleDescJp) {
		this.simpleDescJp = simpleDescJp;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal isExpo;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getIsExpo() {
		return isExpo;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setIsExpo(java.math.BigDecimal isExpo) {
		this.isExpo = isExpo;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private String currencycode;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public String getCurrencycode() {
		return currencycode;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.math.BigDecimal air;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.math.BigDecimal getAir() {
		return air;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setAir(java.math.BigDecimal air) {
		this.air = air;
	}

	/**
	 * This field was generated by CodeBuilder for iBATIS.
	 * 
	 */
	private java.util.Date estOnlineDate;

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public java.util.Date getEstOnlineDate() {
		return estOnlineDate;
	}

	/**
	 * This method was generated by CodeBuilder for iBATIS.
	 */
	public void setEstOnlineDate(java.util.Date estOnlineDate) {
		this.estOnlineDate = estOnlineDate;
	}

}